# Generated by Django 6.0.2 on 2026-04-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20260411_1317'),
        ('store', '0003_order_user_product_seller_cartitem_wishlist'),
    ]

    operations = [
    ]
